# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-07 18:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20180705_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='years_exp',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
